version: '3.9'

services:
  postgres:
    container_name: poj_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - 5432:5432


volumes:
  postgres-db:
    driver: local